TechBlog/Models/PostMetaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TechBlog.Models
{
    public class PostMetaViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string UrlSlug { get; set; }
        public string PostImageSrc { get; set; }
        public string ShortDescription { get; set; }
        public DateTime PostedOn { get; set; }
        public string Username { get; set; }
    }
}

TechBlog/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TechBlog.Models;
using AutoMapper;
using Microsoft.AspNet.Identity;
using BlogDTO;
using BlogEntity.UtilityHelper;
using PagedList;
using TechBlog.API;

namespace TechBlog.Controllers
{
    public class PostsController : Controller
    {
        Client client;
        public PostsController()
        {
            client = new Client();
            ViewBag.categories = client.Get<List<CategoryDTO>>("categories");
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var post = client.Get<PostDTO>("posts/" + id);
            var postviewmodel = Mapper.Map<PostDTO, PostViewModel>(post);
            postviewmodel.PopularTags = client.Get<List<TagDTO>>("tags");
            postviewmodel.RecentPosts = Mapper.Map<List<PostMetaViewModel>>(client.Get<List<PostDTO>>("posts"));
            return View(postviewmodel);
        }
        public ActionResult GetUserPosts(string UserName, int? page)
        {
            var pageIndex = (page ?? 1) - 1;
            var pageSize = 15;
            int totalUserPost = client.Get<int>("posts?Username=" + UserName);
            var posts = client.Get<List<PostDTO>>("posts?Username=" + UserName + "&page=" + page);
            var postmetaviewmodels = Mapper.Map<List<PostDTO>, List<PostMetaViewModel>>(posts);
            var postsAsIPagedList = new StaticPagedList<PostMetaViewModel>(postmetaviewmodels, pageIndex + 1, pageSize, totalUserPost);

            ViewBag.UserName = UserName;
            ViewBag.OnePageOfUserPosts = postsAsIPagedList;
            return View();
        }
       
        public ActionResult RecentPosts()
        {
            var recentPosts = client.Get<List<PostDTO>>("posts");
            List <PostMetaViewModel> postMetaViewModel = new List<PostMetaViewModel>();
            Mapper.Map(recentPosts, postMetaViewModel);
            return View(postMetaViewModel);
        }
        public ActionResult SearchPage()
        {
            List<string> options = new List<string>(new string[] { "Title", "Author", "Tag" });
            ViewBag.option = new SelectList(options);
            return View();
        }
        public ActionResult SearchResult(string term, string option)
        {
            List<PostDTO> posts = new List<PostDTO>();
            List<TagDTO> tags = new List<TagDTO>();
            if (option == "Title" || option == "Author")
                posts = client.Get<List<PostDTO>>("posts?term=" + term + "&option=" + option);
            else
                tags = client.Get<List<TagDTO>>("posts?term=" + Uri.EscapeDataString(term) + "&option=" + option);
            SearchResultViewModel searchResultViewModel = new SearchResultViewModel();
            searchResultViewModel.posts = Mapper.Map<List<PostMetaViewModel>>(posts);
            searchResultViewModel.tags = Mapper.Map<List<TagViewModel>>(tags);
            return PartialView("_SearchResultPartial", searchResultViewModel);
        }
    }
}

TechBlog/Views/Shared/DisplayTemplates/PostDetail.cshtml
@model TechBlog.Models.PostViewModel

@{
    ViewBag.Title = "PostDetail";
}
<div class="row">
    <div class="col-lg-8">
        <h1>@Model.Title</h1>
        <p class="lead">
            <i class="fa fa-user"></i> by <a href="@Url.Action("GetUserPosts", "Posts", new { UserName=Model.Username })">@Model.Username</a>
        </p>
        <hr>
        <p><i class="fa fa-calendar"></i> Posted on @Model.PostedOn</p>
        <p><i class="fa fa-tags"></i> Tags: 
        @foreach (var tag in Model.Tags)
        {
        <a href="/Tags/@tag.Id/@tag.UrlSlug"><span class="badge badge-info">@tag.Name</span></a>
        }
        </p>
        <br />
        <hr>
        @Html.Raw(@Model.Body)
        <hr>
        <div id="commentbody">
            @foreach (var comment in Model.Comments)
            {
                @Html.Partial("_CommentPartial", comment)
            }
        </div>
        <div class="well">
            <h4><i class="fa fa-paper-plane-o"></i> Leave a Comment:</h4>

            @using (Ajax.BeginForm("Create", "Comments", new AjaxOptions
            {
                HttpMethod = "POST",
                InsertionMode = InsertionMode.InsertBefore,
                UpdateTargetId = "commentbody"
            }))
            {
                @Html.Hidden("PostId", Model.Id)
                <div class="form-group">
                    <textarea id="commentb" name="Body" class="form-control" rows="3"></textarea>
                </div>
                if (Request.IsAuthenticated)
                {
                    <button id="addcomment" type="submit" class="btn btn-primary"><i class="fa fa-reply"></i> Submit</button>
                }
            }
        </div>
    </div>
    <div class="col-lg-4">
        <div class="well">
            <h4><i class="fa fa-tags"></i> Popular Tags:</h4>
            <div class="row">
                @foreach (var tag in Model.PopularTags)
                {
                    <div class="col-lg-6">
                        <a href="/Tags/@tag.Id/@tag.UrlSlug"><span class="badge badge-info">@tag.Name</span></a>
                    </div>
                }
            </div>
        </div>
       
        <div class="well">
            <h4><i class="fa fa-fire"></i> Recent Posts:</h4>
            <ul>
                @foreach (var post in Model.RecentPosts)
                {
                    <li><a href="/Posts/@post.Id/@post.UrlSlug">@post.Title</a></li>
                }
            </ul>
        </div>
        </div>

</div>

TechBlog/Views/Shared/DisplayTemplates/PostMeta.cshtml
@using Microsoft.AspNet.Identity;
@model TechBlog.Models.PostMetaViewModel

@{
    ViewBag.Title = "PostMeta";
}

<div class="col-md-4">
    <div class="display">
        <a href="/Posts/@Model.Id/@Model.UrlSlug">
            <img class="image" src="@Model.PostImageSrc" />
            <span class="author">by @Model.Username</span>
        </a>
    </div>
    <a href="/Posts/@Model.Id/@Model.UrlSlug"><h2>@Model.Title</h2></a>
    <p>@Model.ShortDescription</p>
    @if (Request.IsAuthenticated && User.Identity.GetUserName() == Model.Username)
    {
        <p>
            <a class="btn btn-default" href="@Url.Action("Edit", "ManagePosts", new  { id=Model.Id, urlslug=Model.UrlSlug })">Edit &raquo;</a>
            <a class="btn btn-danger" href="@Url.Action("Delete", "ManagePosts", new  { id=Model.Id, urlslug=Model.UrlSlug })">Delete &raquo;</a>
        </p>
    }
</div>